// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX48zIAN2LDFlp5fcXFp3NkIqqt-rbZgY',
    appId: '1:562429955432:web:1771e0c8af2129b1939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    authDomain: 'shabakacourse.firebaseapp.com',
    storageBucket: 'shabakacourse.firebasestorage.app',
    measurementId: 'G-PZQCTFB8VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCveKWpXJe_WQHxQjv_034XorEVlm0ZrE4',
    appId: '1:562429955432:android:d22c6e8bb76cd348939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXF8BZn--ayzw0hxOd1S8WL4xzlr1ctVU',
    appId: '1:562429955432:ios:70b0074fe0efb483939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
    iosBundleId: 'com.example.shabakahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXF8BZn--ayzw0hxOd1S8WL4xzlr1ctVU',
    appId: '1:562429955432:ios:70b0074fe0efb483939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    storageBucket: 'shabakacourse.firebasestorage.app',
    iosBundleId: 'com.example.shabakahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX48zIAN2LDFlp5fcXFp3NkIqqt-rbZgY',
    appId: '1:562429955432:web:738c032b0dd9a6e5939add',
    messagingSenderId: '562429955432',
    projectId: 'shabakacourse',
    authDomain: 'shabakacourse.firebaseapp.com',
    storageBucket: 'shabakacourse.firebasestorage.app',
    measurementId: 'G-H6J8JH52DC',
  );
}
